name: Build and Deploy Flutter Web (mock & server)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: mock
            base_href: /pitch_mock/
            external_repo: tonytmtsh/pitch_mock
            backend: mock
          - name: server
            base_href: /pitch_server/
            external_repo: tonytmtsh/pitch_server
            backend: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Enable web
        run: flutter config --enable-web

      - name: Pub get
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --reporter compact

      - name: Build web (mock)
        if: ${{ matrix.name == 'mock' }}
        run: >-
          flutter build web --release
          --base-href "${{ matrix.base_href }}"
          --dart-define=BACKEND=${{ matrix.backend }}

      - name: Build web (server)
        if: ${{ matrix.name == 'server' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          flutter build web --release \
            --base-href "${{ matrix.base_href }}" \
            --dart-define=BACKEND=${{ matrix.backend }} \
            --dart-define=SUPABASE_URL="$SUPABASE_URL" \
            --dart-define=SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY"

      - name: Deploy to GitHub Pages (${{ matrix.name }})
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}
          external_repository: ${{ matrix.external_repo }}
          publish_branch: gh-pages
          publish_dir: ./build/web
          force_orphan: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com

      - name: Wait for GitHub Pages deployment
        run: sleep 30

      - name: Smoke test GitHub Pages (${{ matrix.name }})
        run: |
          set -e
          PAGES_URL="https://tonytmtsh.github.io${{ matrix.base_href }}"
          echo "Testing Pages URL: $PAGES_URL"
          
          # Retry logic with exponential backoff
          max_attempts=5
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts..."
            
            if curl -f -s -L "$PAGES_URL" | grep -q '<title>'; then
              echo "✅ Smoke test passed for ${{ matrix.name }} - Pages site is accessible"
              exit 0
            fi
            
            if [ $attempt -eq $max_attempts ]; then
              echo "❌ Smoke test failed for ${{ matrix.name }} - Pages site not accessible after $max_attempts attempts"
              exit 1
            fi
            
            sleep_time=$((attempt * 15))
            echo "Retrying in ${sleep_time} seconds..."
            sleep $sleep_time
            attempt=$((attempt + 1))
          done
