name: Build and Deploy Flutter Web (mock & server)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: mock
            base_href: /pitch_mock/
            external_repo: tonytmtsh/pitch_mock
            backend: mock
          - name: server
            base_href: /pitch_server/
            external_repo: tonytmtsh/pitch_server
            backend: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Enable web
        run: flutter config --enable-web

      - name: Pub get
        run: flutter pub get

      - name: Run tests
        run: flutter test --reporter compact

      - name: Build web (mock)
        if: ${{ matrix.name == 'mock' }}
        run: >-
          flutter build web --release
          --base-href "${{ matrix.base_href }}"
          --dart-define=BACKEND=${{ matrix.backend }}

      - name: Build web (server)
        if: ${{ matrix.name == 'server' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          flutter build web --release \
            --base-href "${{ matrix.base_href }}" \
            --dart-define=BACKEND=${{ matrix.backend }} \
            --dart-define=SUPABASE_URL="$SUPABASE_URL" \
            --dart-define=SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY"

      - name: Deploy to GitHub Pages (${{ matrix.name }})
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}
          external_repository: ${{ matrix.external_repo }}
          publish_branch: gh-pages
          publish_dir: ./build/web
          force_orphan: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
